version: "2.1"

services:
  app:
    container_name: testeContele_app
    build: .
    entrypoint: ./entrypoint.sh
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_CLIENT: pg
      DB_PASSWORD: 123
      DB_DATABASE: TestDeveloperFullStackContele
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    container_name: testeContele_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: TestDeveloperFullStackContele
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5