version: "3.7"

services:
  app:
    container_name: testeContele
    build: .
    environment:
      DB_HOST: postgres
    ports:
      - 3000:3000
    depends_on:
      - postgres
  
  db:
    image: postgres
    container_name: testeContele
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: TestDeveloperFullStackContele
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

